# Generated by Django 5.2.1 on 2025-12-09 17:02

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('formulario', '0004_alter_inscritoconvenio_dthinscricao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prontuario',
            fields=[
                ('idprontuario', models.AutoField(primary_key=True, serialize=False)),
                ('dth_abertura', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Abertura')),
                ('status_ativo', models.BooleanField(default=True, verbose_name='Em Atendimento')),
                ('tcle_assinado', models.FileField(blank=True, null=True, upload_to='tcle/', verbose_name='TCLE Assinado')),
                ('coordenador', models.ForeignKey(limit_choices_to={'cargo': 'COORD'}, on_delete=django.db.models.deletion.PROTECT, related_name='prontuarios_coordenador', to=settings.AUTH_USER_MODEL, verbose_name='Coordenador Geral')),
                ('estagiario', models.ForeignKey(limit_choices_to={'cargo': 'ESTAG'}, on_delete=django.db.models.deletion.PROTECT, related_name='prontuarios_estagiario', to=settings.AUTH_USER_MODEL, verbose_name='Estagiário Responsável')),
                ('paciente_comunidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='formulario.inscritocomunidade', verbose_name='Paciente (Comunidade)')),
                ('paciente_convenio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='formulario.inscritoconvenio', verbose_name='Paciente (Convénio)')),
                ('supervisor', models.ForeignKey(limit_choices_to={'cargo': 'SUPER'}, on_delete=django.db.models.deletion.PROTECT, related_name='prontuarios_supervisor', to=settings.AUTH_USER_MODEL, verbose_name='Supervisor')),
            ],
            options={
                'verbose_name': 'Prontuário (Vínculo)',
                'verbose_name_plural': 'Prontuários',
                'db_table': 'prontuario',
            },
        ),
        migrations.CreateModel(
            name='Evolucao',
            fields=[
                ('idevolucao', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.TextField(help_text='Descreva brevemente como foi o atendimento.', validators=[django.core.validators.MaxLengthValidator(500)], verbose_name='Comentário sobre a consulta (Máx 500 caracteres)')),
                ('data_atendimento', models.DateField(verbose_name='Data da Consulta')),
                ('dth_registro', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Registrado em')),
                ('prontuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evolucoes', to='coodernador.prontuario', verbose_name='Paciente Vinculado')),
            ],
            options={
                'verbose_name': 'Anotação de Consulta',
                'verbose_name_plural': 'Anotações de Consultas',
                'db_table': 'evolucao',
                'ordering': ['-data_atendimento'],
            },
        ),
    ]
