# Generated by Django 5.2.1 on 2026-03-19 12:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coodernador', '0001_initial'),
        ('formulario', '0007_alter_inscritocomunidade_identidadegenero_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='prontuario',
            index=models.Index(fields=['estagiario', 'status_ativo'], name='idx_pront_estag_status'),
        ),
        migrations.AddIndex(
            model_name='prontuario',
            index=models.Index(fields=['status_ativo'], name='idx_pront_status'),
        ),
        migrations.AddIndex(
            model_name='prontuario',
            index=models.Index(fields=['paciente_comunidade'], name='idx_pront_pac_comun'),
        ),
        migrations.AddIndex(
            model_name='prontuario',
            index=models.Index(fields=['paciente_convenio'], name='idx_pront_pac_conv'),
        ),
        migrations.AddIndex(
            model_name='prontuario',
            index=models.Index(fields=['supervisor'], name='idx_pront_supervisor'),
        ),
    ]
