# Generated by Django 5.1.7 on 2026-05-11 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coodernador', '0002_prontuario_idx_pront_estag_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prontuario',
            options={'ordering': ['-dth_abertura'], 'verbose_name': 'Prontuário (Vínculo)', 'verbose_name_plural': 'Prontuários'},
        ),
    ]
