# Generated by Django 5.2.7 on 2025-10-30 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Inscritocomunidade",
            fields=[
                (
                    "idfichacomunidade",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("nomeinscrito", models.CharField(max_length=100)),
                ("dtnascimento", models.DateField()),
                ("nomeresp", models.CharField(blank=True, max_length=50, null=True)),
                ("grauresp", models.CharField(blank=True, max_length=25, null=True)),
                (
                    "cpfresp",
                    models.CharField(blank=True, max_length=15, null=True, unique=True),
                ),
                (
                    "estadocivilresp",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Solteiro", "Solteiro"),
                            ("Casado", "Casado"),
                            ("Divorciado", "Divorciado"),
                            ("Viúvo", "Viúvo"),
                            ("União Estável", "União Estável"),
                            ("Nenhum", "Nenhum"),
                            ("Outros", "Outros"),
                        ],
                        max_length=25,
                        null=True,
                    ),
                ),
                (
                    "tellcellresp",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("emailresp", models.CharField(blank=True, max_length=45, null=True)),
                (
                    "estadocivilinscrito",
                    models.CharField(
                        choices=[
                            ("Solteiro", "Solteiro"),
                            ("Casado", "Casado"),
                            ("Divorciado", "Divorciado"),
                            ("Viúvo", "Viúvo"),
                            ("União Estável", "União Estável"),
                            ("Nenhum", "Nenhum"),
                            ("Outros", "Outros"),
                        ],
                        max_length=25,
                    ),
                ),
                ("cpfinscrito", models.CharField(max_length=15, unique=True)),
                ("tellcellinscrito", models.CharField(max_length=20)),
                ("contatourgencia", models.CharField(max_length=15)),
                ("nomecontatourgencia", models.CharField(max_length=50)),
                ("emailinscrito", models.CharField(max_length=45)),
                (
                    "identidadegenero",
                    models.CharField(
                        choices=[
                            ("Masculino", "Masculino"),
                            ("Feminino", "Feminino"),
                            ("Não Binário", "Não Binário"),
                            ("Transgênero", "Transgênero"),
                            ("Outros", "Outros"),
                        ],
                        max_length=25,
                    ),
                ),
                (
                    "etnia",
                    models.CharField(
                        choices=[
                            ("Branca", "Branca"),
                            ("Preta", "Preta"),
                            ("Parda", "Parda"),
                            ("Amarela", "Amarela"),
                            ("Indígena", "Indígena"),
                            ("Outras", "Outras"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "religiao",
                    models.CharField(
                        choices=[
                            ("Católico", "Católico"),
                            ("Evangélico", "Evangélico"),
                            ("Budismo", "Budismo"),
                            ("Espirita", "Espirita"),
                            ("Hinduísmo", "Hinduísmo"),
                            ("Islamismo", "Islamismo"),
                            ("Judaismo", "Judaismo"),
                            (
                                "Religião de Matriz Africana",
                                "Religião de Matriz Africana",
                            ),
                            ("Sem religião", "Sem religião"),
                            ("Outros", "Outros"),
                        ],
                        max_length=30,
                    ),
                ),
                ("confirmlgpd", models.BooleanField(default=False)),
                ("dthinscricao", models.DateField(auto_now_add=True)),
                ("status", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "inscritocomunidade",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Inscritoconvenio",
            fields=[
                (
                    "idfichaconvenio",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("nomeinscrito", models.CharField(max_length=100)),
                ("dtnascimento", models.DateField()),
                ("testavpsico", models.BooleanField()),
                ("tipoencaminhamento", models.CharField(max_length=50)),
                ("nomeresp", models.CharField(blank=True, max_length=50, null=True)),
                ("grauresp", models.CharField(blank=True, max_length=25, null=True)),
                (
                    "cpfresp",
                    models.CharField(blank=True, max_length=15, null=True, unique=True),
                ),
                (
                    "estadocivilresp",
                    models.CharField(blank=True, max_length=25, null=True),
                ),
                (
                    "tellcellresp",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("emailresp", models.CharField(blank=True, max_length=45, null=True)),
                (
                    "estadocivilinscrito",
                    models.CharField(blank=True, max_length=25, null=True),
                ),
                ("cpfinscrito", models.CharField(max_length=15, unique=True)),
                ("tellcellinscrito", models.CharField(max_length=20)),
                ("contatourgencia", models.CharField(max_length=15)),
                ("emailinscrito", models.CharField(max_length=50)),
                ("identidadegenero", models.CharField(max_length=25)),
                ("etnia", models.CharField(max_length=15)),
                ("religiao", models.CharField(max_length=30)),
                ("confirmlgpd", models.BooleanField()),
                ("dthinscricao", models.DateField()),
                ("status", models.BooleanField(blank=True, null=True)),
            ],
            options={
                "db_table": "inscritoconvenio",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Endereco",
            fields=[
                ("idendereco", models.AutoField(primary_key=True, serialize=False)),
                ("cidade", models.CharField(max_length=40)),
                ("bairro", models.CharField(blank=True, max_length=50, null=True)),
                ("rua", models.CharField(max_length=100)),
                ("uf", models.CharField(default="DF", max_length=2)),
                ("cep", models.CharField(max_length=9, unique=True)),
                (
                    "idfichacomunidade",
                    models.ForeignKey(
                        blank=True,
                        db_column="idfichacomunidade",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="formulario.inscritocomunidade",
                    ),
                ),
                (
                    "idfichaconvenio",
                    models.ForeignKey(
                        blank=True,
                        db_column="idfichaconvenio",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="formulario.inscritoconvenio",
                    ),
                ),
            ],
            options={
                "db_table": "endereco",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Doencafisica",
            fields=[
                ("iddoencafisica", models.AutoField(primary_key=True, serialize=False)),
                ("doencaresp", models.BooleanField(blank=True, null=True)),
                ("cancer", models.BooleanField(blank=True, null=True)),
                ("diabete", models.BooleanField(blank=True, null=True)),
                ("disfusexual", models.BooleanField(blank=True, null=True)),
                ("doencadgt", models.BooleanField(blank=True, null=True)),
                ("escleorosemlt", models.BooleanField(blank=True, null=True)),
                ("hcpt", models.BooleanField(blank=True, null=True)),
                ("luposatm", models.BooleanField(blank=True, null=True)),
                ("obesidade", models.BooleanField(blank=True, null=True)),
                ("pblmarenal", models.BooleanField(blank=True, null=True)),
                ("outro", models.BooleanField(blank=True, null=True)),
                (
                    "idfichacomunidade",
                    models.ForeignKey(
                        blank=True,
                        db_column="idfichacomunidade",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="formulario.inscritocomunidade",
                    ),
                ),
                (
                    "idfichaconvenio",
                    models.ForeignKey(
                        blank=True,
                        db_column="idfichaconvenio",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="formulario.inscritoconvenio",
                    ),
                ),
            ],
            options={
                "db_table": "doencafisica",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Disponibilidade",
            fields=[
                (
                    "iddisponibilidade",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("manha", models.BooleanField(blank=True, null=True)),
                ("tarde", models.BooleanField(blank=True, null=True)),
                ("noite", models.BooleanField(blank=True, null=True)),
                ("sabado", models.BooleanField(blank=True, null=True)),
                (
                    "idfichacomunidade",
                    models.ForeignKey(
                        blank=True,
                        db_column="idfichacomunidade",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="disponibilidades",
                        to="formulario.inscritocomunidade",
                    ),
                ),
                (
                    "idfichaconvenio",
                    models.ForeignKey(
                        blank=True,
                        db_column="idfichaconvenio",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="formulario.inscritoconvenio",
                    ),
                ),
            ],
            options={
                "db_table": "disponibilidade",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Medicamento",
            fields=[
                ("idmedicamento", models.AutoField(primary_key=True, serialize=False)),
                ("ansiolitico", models.BooleanField(blank=True, null=True)),
                ("antidepressivo", models.BooleanField(blank=True, null=True)),
                ("antipsicotico", models.BooleanField(blank=True, null=True)),
                ("estabhumor", models.BooleanField(blank=True, null=True)),
                ("memoriatct", models.BooleanField(blank=True, null=True)),
                ("outro", models.BooleanField(blank=True, null=True)),
                (
                    "idfichacomunidade",
                    models.ForeignKey(
                        blank=True,
                        db_column="idfichacomunidade",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="formulario.inscritocomunidade",
                    ),
                ),
                (
                    "idfichaconvenio",
                    models.ForeignKey(
                        blank=True,
                        db_column="idfichaconvenio",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="formulario.inscritoconvenio",
                    ),
                ),
            ],
            options={
                "db_table": "medicamento",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Motivoacompanhamento",
            fields=[
                ("idmotivoacamp", models.AutoField(primary_key=True, serialize=False)),
                ("ansiedade", models.BooleanField(blank=True, null=True)),
                ("assediomoral", models.BooleanField(blank=True, null=True)),
                ("depressao", models.BooleanField(blank=True, null=True)),
                ("dfaprendizagem", models.BooleanField(blank=True, null=True)),
                ("humorinstavel", models.BooleanField(blank=True, null=True)),
                ("insonia", models.BooleanField(blank=True, null=True)),
                ("isolasocial", models.BooleanField(blank=True, null=True)),
                ("luto", models.BooleanField(blank=True, null=True)),
                ("tristeza", models.BooleanField(blank=True, null=True)),
                ("apatia", models.BooleanField(blank=True, null=True)),
                ("chorofc", models.BooleanField(blank=True, null=True)),
                ("exaustao", models.BooleanField(blank=True, null=True)),
                ("fadiga", models.BooleanField(blank=True, null=True)),
                ("faltanimo", models.BooleanField(blank=True, null=True)),
                ("vldt", models.BooleanField(blank=True, null=True)),
                ("assediosexual", models.BooleanField(blank=True, null=True)),
                ("outro", models.BooleanField(blank=True, null=True)),
                (
                    "idfichacomunidade",
                    models.ForeignKey(
                        blank=True,
                        db_column="idfichacomunidade",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="formulario.inscritocomunidade",
                    ),
                ),
                (
                    "idfichaconvenio",
                    models.ForeignKey(
                        blank=True,
                        db_column="idfichaconvenio",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="formulario.inscritoconvenio",
                    ),
                ),
            ],
            options={
                "db_table": "motivoacompanhamento",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Pcdsnd",
            fields=[
                ("idpcdnd", models.AutoField(primary_key=True, serialize=False)),
                ("tea", models.BooleanField(blank=True, null=True)),
                ("tdah", models.BooleanField(blank=True, null=True)),
                ("dffs", models.BooleanField(blank=True, null=True)),
                ("dfv", models.BooleanField(blank=True, null=True)),
                ("dfa", models.BooleanField(blank=True, null=True)),
                ("ttap", models.BooleanField(blank=True, null=True)),
                ("ahst", models.BooleanField(blank=True, null=True)),
                ("outro", models.BooleanField(blank=True, null=True)),
                (
                    "idfichacomunidade",
                    models.ForeignKey(
                        blank=True,
                        db_column="idfichacomunidade",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="formulario.inscritocomunidade",
                    ),
                ),
                (
                    "idfichaconvenio",
                    models.ForeignKey(
                        blank=True,
                        db_column="idfichaconvenio",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="formulario.inscritoconvenio",
                    ),
                ),
            ],
            options={
                "db_table": "pcdsnd",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Tipoterapia",
            fields=[
                ("idtipoterapia", models.AutoField(primary_key=True, serialize=False)),
                ("individualift", models.BooleanField(blank=True, null=True)),
                ("individualadt", models.BooleanField(blank=True, null=True)),
                ("individualadto", models.BooleanField(blank=True, null=True)),
                ("individualids", models.BooleanField(blank=True, null=True)),
                ("familia", models.BooleanField(blank=True, null=True)),
                ("grupo", models.BooleanField(blank=True, null=True)),
                ("casal", models.BooleanField(blank=True, null=True)),
                (
                    "idfichacomunidade",
                    models.ForeignKey(
                        blank=True,
                        db_column="idfichacomunidade",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="tipoterapias",
                        to="formulario.inscritocomunidade",
                    ),
                ),
                (
                    "idfichaconvenio",
                    models.ForeignKey(
                        blank=True,
                        db_column="idfichaconvenio",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="formulario.inscritoconvenio",
                    ),
                ),
            ],
            options={
                "db_table": "tipoterapia",
                "managed": True,
            },
        ),
    ]
