# Generated by Django 5.2.1 on 2025-11-01 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0002_alter_endereco_cep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscritoconvenio',
            name='testavpsico',
            field=models.BooleanField(null=True),
        ),
    ]
