# Generated by Django 5.2.1 on 2025-11-01 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0003_alter_inscritoconvenio_testavpsico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscritoconvenio',
            name='dthinscricao',
            field=models.DateField(auto_now_add=True),
        ),
    ]
