# Generated by Django 5.2.1 on 2025-12-09 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0004_alter_inscritoconvenio_dthinscricao'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='inscritocomunidade',
            index=models.Index(fields=['dthinscricao'], name='idx_dthinsc_comun'),
        ),
        migrations.AddIndex(
            model_name='inscritoconvenio',
            index=models.Index(fields=['dthinscricao'], name='idx_dthinsc_conv'),
        ),
    ]
