# Generated by Django 5.2.1 on 2026-03-19 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0006_contatourgencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscritocomunidade',
            name='identidadegenero',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino'), ('Não Binário', 'Não Binário'), ('Transgênero', 'Transgênero'), ('Outros', 'Outros'), ('Prefiro não dizer', 'Prefiro não dizer')], max_length=25),
        ),
        migrations.AddIndex(
            model_name='inscritocomunidade',
            index=models.Index(fields=['cpfinscrito'], name='idx_cpf_inscr_comun'),
        ),
        migrations.AddIndex(
            model_name='inscritocomunidade',
            index=models.Index(fields=['status'], name='idx_status_comun'),
        ),
        migrations.AddIndex(
            model_name='inscritocomunidade',
            index=models.Index(fields=['status', 'dthinscricao'], name='idx_status_dt_comun'),
        ),
        migrations.AddIndex(
            model_name='inscritoconvenio',
            index=models.Index(fields=['cpfinscrito'], name='idx_cpf_inscr_conv'),
        ),
        migrations.AddIndex(
            model_name='inscritoconvenio',
            index=models.Index(fields=['status'], name='idx_status_conv'),
        ),
    ]
