# Generated by Django 5.2.1 on 2025-11-17 18:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('matricula', models.CharField(max_length=20, unique=True, verbose_name='Matrícula/RA')),
                ('nome_completo', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('email_institucional', models.EmailField(max_length=254, unique=True, verbose_name='E-mail Institucional')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de nascimento')),
                ('cargo', models.CharField(choices=[('COORD', 'Coordenador Geral'), ('SUPER', 'Supervisor'), ('RESP_TEC', 'Responsável Técnico'), ('ESTAG', 'Estagiário'), ('SEC', 'Secretária')], max_length=20, verbose_name='Cargo')),
                ('crp', models.CharField(blank=True, max_length=20, null=True, verbose_name='CRP')),
                ('semestre', models.CharField(blank=True, max_length=20, null=True)),
                ('dth_insert', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Criação')),
                ('dth_delete', models.DateTimeField(blank=True, null=True)),
                ('status_delete', models.BooleanField(default=False, verbose_name='Excluído')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Acesso ao Admin')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'db_table': 'usuario',
            },
        ),
    ]
