# Generated by Django 5.2.1 on 2025-11-18 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='email_institucional',
            new_name='email',
        ),
        migrations.AddField(
            model_name='usuario',
            name='documento_crp',
            field=models.FileField(blank=True, null=True, upload_to='docs_crp/', verbose_name='Upload Documento CRP'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='nivel_estagio',
            field=models.CharField(blank=True, choices=[('BASICO', 'Básico'), ('AVANCADO', 'Avançado')], max_length=10, null=True, verbose_name='Nível do Estágio'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='supervisor_vinculado',
            field=models.ForeignKey(blank=True, limit_choices_to={'cargo': 'SUPER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estagiarios_supervisionados', to=settings.AUTH_USER_MODEL, verbose_name='Supervisor Responsável'),
        ),
    ]
