# Generated by Django 5.2.1 on 2025-12-09 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_rename_email_institucional_usuario_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='documento_crp',
        ),
    ]
