# Generated by Django 5.2.1 on 2025-12-13 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_remove_usuario_documento_crp'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='abordagem_teorica',
            field=models.CharField(blank=True, choices=[('TCC', 'Terapia Cognitivo-Comportamental'), ('Psicanalise', 'Psicanálise'), ('Humanista', 'Humanista / Fenomenológica'), ('Sistemica', 'Sistêmica'), ('AnaliseComportamento', 'Análise do Comportamento')], max_length=30, null=True, verbose_name='Abordagem Teórica'),
        ),
    ]
