# Generated by Django 5.2.1 on 2025-12-16 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('usuarios', '0004_usuario_abordagem_teorica'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='foto_perfil',
            field=models.ImageField(blank=True, help_text='Formatos aceitos: JPG, PNG. Tamanho máximo: 5MB', null=True, upload_to='usuarios/fotos_perfil/', verbose_name='Foto de Perfil'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['cargo'], name='idx_usuario_cargo'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['cpf'], name='idx_usuario_cpf'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['matricula'], name='idx_usuario_matricula'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['supervisor_vinculado'], name='idx_usuario_supervisor'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['status_delete', 'is_active'], name='idx_usuario_status'),
        ),
    ]
