# Generated by Django 5.2.1 on 2026-04-14 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_usuario_foto_perfil_usuario_idx_usuario_cargo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto_perfil',
            field=models.FileField(blank=True, help_text='Formatos aceitos: JPG, PNG. Tamanho máximo: 5MB', null=True, upload_to='usuarios/fotos_perfil/', verbose_name='Foto de Perfil'),
        ),
    ]
